
server:
  port: 9090
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    url: jdbc:postgresql://localhost:5432/ecom_db
    database: ecom_db
    username: postgres
    generateDDL: true
  jpa:
    hibernate:
      ddl-auto: create
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

h12:
  ecommerce:
    db:
      password: postgres
      username: postgres
      url: jdbc:postgresql://localhost:5432/ecom_db
