name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  GIT_TRACE: 1
  GIT_CURL_VERBOSE: 1
  TOKEN: ${{ secrets.GIT_TOKEN}}

jobs:
  print_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secrets
        run: |
          for secret in $(env | grep '^SECRET_' | cut -d= -f1); do
            echo "Secret Name: $secret"
            echo "Secret Value: ${!secret}"
          done
#        retention-days: 1


  build:
    name: Gradle build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
#        server-username: ${{ secrets.USERNAME_GITHUB || github.token }}
#        server-password: ${{ secrets.TOKEN_GITHUB || github.token }}
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Present Working directory
        run: ls -la

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

  publish:
    name: Publish jar
    needs: build
    runs-on: ubuntu-latest

    steps:
#      - name: checkout code
#        uses: actions/checkout@v3
#
#      - name: Set up Java
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'adopt'
#
#      - name: Present working directory
#        run: ls -la
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#
#      - name: Gradle Build
#        run: ./gradlew clean build
#
#      - name: Publish package
#        run: ./gradlew clean build publish
